"""Senior Architect Upgrade Retry

Revision ID: 2b19e13c6cb1
Revises: df1802f174bc
Create Date: 2026-02-18 22:02:27.342734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b19e13c6cb1'
down_revision: Union[str, None] = 'df1802f174bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athlete_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('strength_level', sa.Enum('BEGINNER', 'NOVICE', 'INTERMEDIATE', 'ADVANCED', 'ELITE', name='strengthlevel'), nullable=True),
    sa.Column('boxing_level', sa.Enum('AMATEUR', 'CLUB_FIGHTER', 'ADVANCED', 'ELITE', 'PRO', name='boxinglevel'), nullable=True),
    sa.Column('hybrid_level_score', sa.Float(), nullable=True),
    sa.Column('hybrid_label', sa.String(), nullable=True),
    sa.Column('source_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athlete_levels_id'), 'athlete_levels', ['id'], unique=False)
    op.create_table('monthly_nutrition_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.DateTime(), nullable=True),
    sa.Column('monthly_calorie_target', sa.Integer(), nullable=True),
    sa.Column('current_monthly_calories', sa.Integer(), nullable=True),
    sa.Column('projected_weight_change', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_nutrition_goals_id'), 'monthly_nutrition_goals', ['id'], unique=False)
    op.create_table('performance_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('forecast_date', sa.DateTime(), nullable=True),
    sa.Column('one_rm_bench_projection', sa.Float(), nullable=True),
    sa.Column('one_rm_squat_projection', sa.Float(), nullable=True),
    sa.Column('one_rm_deadlift_projection', sa.Float(), nullable=True),
    sa.Column('body_weight_projection', sa.Float(), nullable=True),
    sa.Column('conditioning_score_projection', sa.Float(), nullable=True),
    sa.Column('confidence_interval', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_forecasts_id'), 'performance_forecasts', ['id'], unique=False)
    op.add_column('recovery_scores', sa.Column('sleep_quality', sa.Integer(), nullable=True))
    op.add_column('recovery_scores', sa.Column('resting_heart_rate', sa.Integer(), nullable=True))
    op.add_column('recovery_scores', sa.Column('soreness', sa.Integer(), nullable=True))
    op.add_column('recovery_scores', sa.Column('stress', sa.Integer(), nullable=True))
    op.add_column('recovery_scores', sa.Column('hydration_level', sa.Integer(), nullable=True))
    op.add_column('recovery_scores', sa.Column('mood', sa.String(), nullable=True))
    op.add_column('recovery_scores', sa.Column('cold_exposure_minutes', sa.Integer(), nullable=True))
    op.add_column('recovery_scores', sa.Column('sauna_minutes', sa.Integer(), nullable=True))
    op.add_column('recovery_scores', sa.Column('mobility_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recovery_scores', 'mobility_minutes')
    op.drop_column('recovery_scores', 'sauna_minutes')
    op.drop_column('recovery_scores', 'cold_exposure_minutes')
    op.drop_column('recovery_scores', 'mood')
    op.drop_column('recovery_scores', 'hydration_level')
    op.drop_column('recovery_scores', 'stress')
    op.drop_column('recovery_scores', 'soreness')
    op.drop_column('recovery_scores', 'resting_heart_rate')
    op.drop_column('recovery_scores', 'sleep_quality')
    op.drop_index(op.f('ix_performance_forecasts_id'), table_name='performance_forecasts')
    op.drop_table('performance_forecasts')
    op.drop_index(op.f('ix_monthly_nutrition_goals_id'), table_name='monthly_nutrition_goals')
    op.drop_table('monthly_nutrition_goals')
    op.drop_index(op.f('ix_athlete_levels_id'), table_name='athlete_levels')
    op.drop_table('athlete_levels')
    # ### end Alembic commands ###
