"""Recovery Engine V3

Revision ID: 6e8d217524b8
Revises: 2b19e13c6cb1
Create Date: 2026-02-18 22:12:37.829780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e8d217524b8'
down_revision: Union[str, None] = '2b19e13c6cb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_logs_v3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('sleep_duration', sa.Float(), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('hrv', sa.Integer(), nullable=True),
    sa.Column('resting_heart_rate', sa.Integer(), nullable=True),
    sa.Column('muscle_soreness', sa.Integer(), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('hydration_liters', sa.Float(), nullable=True),
    sa.Column('mood', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_logs_v3_id'), 'recovery_logs_v3', ['id'], unique=False)
    op.create_table('recovery_method_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('method_type', sa.Enum('COLD_EXPOSURE', 'SAUNA', 'MOBILITY', 'MASSAGE', 'ACTIVE_RECOVERY', name='recoverymethodtype'), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_method_logs_id'), 'recovery_method_logs', ['id'], unique=False)
    op.create_table('recovery_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('recommendation_text', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_recommendations_id'), 'recovery_recommendations', ['id'], unique=False)
    op.create_table('recovery_scores_v3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('sleep_component', sa.Float(), nullable=True),
    sa.Column('hrv_component', sa.Float(), nullable=True),
    sa.Column('rhr_component', sa.Float(), nullable=True),
    sa.Column('soreness_component', sa.Float(), nullable=True),
    sa.Column('stress_component', sa.Float(), nullable=True),
    sa.Column('hydration_component', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_scores_v3_id'), 'recovery_scores_v3', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_scores_v3_id'), table_name='recovery_scores_v3')
    op.drop_table('recovery_scores_v3')
    op.drop_index(op.f('ix_recovery_recommendations_id'), table_name='recovery_recommendations')
    op.drop_table('recovery_recommendations')
    op.drop_index(op.f('ix_recovery_method_logs_id'), table_name='recovery_method_logs')
    op.drop_table('recovery_method_logs')
    op.drop_index(op.f('ix_recovery_logs_v3_id'), table_name='recovery_logs_v3')
    op.drop_table('recovery_logs_v3')
    # ### end Alembic commands ###
