"""Nutrition V2 and Body Progress

Revision ID: 9890136d0c8f
Revises: 6e8d217524b8
Create Date: 2026-02-18 22:20:13.646347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9890136d0c8f'
down_revision: Union[str, None] = '6e8d217524b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_progress_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('start_weight', sa.Float(), nullable=True),
    sa.Column('end_weight', sa.Float(), nullable=True),
    sa.Column('total_weight_change', sa.Float(), nullable=True),
    sa.Column('estimated_muscle_gain', sa.Float(), nullable=True),
    sa.Column('estimated_fat_gain', sa.Float(), nullable=True),
    sa.Column('estimated_fat_loss', sa.Float(), nullable=True),
    sa.Column('avg_calorie_surplus_deficit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_body_progress_summaries_id'), 'body_progress_summaries', ['id'], unique=False)
    op.create_table('body_weight_logs_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('body_fat_percentage', sa.Float(), nullable=True),
    sa.Column('muscle_mass_estimate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_body_weight_logs_v2_id'), 'body_weight_logs_v2', ['id'], unique=False)
    op.create_table('monthly_calorie_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('daily_calorie_target', sa.Integer(), nullable=True),
    sa.Column('monthly_calorie_target', sa.Integer(), nullable=True),
    sa.Column('calories_consumed_so_far', sa.Integer(), nullable=True),
    sa.Column('surplus_or_deficit', sa.Integer(), nullable=True),
    sa.Column('projected_weight_change', sa.Float(), nullable=True),
    sa.Column('goal_type', sa.Enum('BULK', 'CUT', 'MAINTENANCE', name='nutritiongoaltype'), nullable=True),
    sa.Column('protein_compliance_pct', sa.Float(), nullable=True),
    sa.Column('carb_consistency_pct', sa.Float(), nullable=True),
    sa.Column('hydration_adherence_pct', sa.Float(), nullable=True),
    sa.Column('micronutrient_score', sa.Float(), nullable=True),
    sa.Column('monthly_nutrition_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_calorie_summaries_id'), 'monthly_calorie_summaries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monthly_calorie_summaries_id'), table_name='monthly_calorie_summaries')
    op.drop_table('monthly_calorie_summaries')
    op.drop_index(op.f('ix_body_weight_logs_v2_id'), table_name='body_weight_logs_v2')
    op.drop_table('body_weight_logs_v2')
    op.drop_index(op.f('ix_body_progress_summaries_id'), table_name='body_progress_summaries')
    op.drop_table('body_progress_summaries')
    # ### end Alembic commands ###
