"""Initial schema

Revision ID: df1802f174bc
Revises: 
Create Date: 2026-02-18 21:41:48.119197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df1802f174bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biometric_timeseries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('metric_type', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biometric_timeseries_id'), 'biometric_timeseries', ['id'], unique=False)
    op.create_index(op.f('ix_biometric_timeseries_metric_type'), 'biometric_timeseries', ['metric_type'], unique=False)
    op.create_table('community_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('post_type', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_posts_id'), 'community_posts', ['id'], unique=False)
    op.create_table('daily_habit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('habit_type', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_habit_logs_habit_type'), 'daily_habit_logs', ['habit_type'], unique=False)
    op.create_index(op.f('ix_daily_habit_logs_id'), 'daily_habit_logs', ['id'], unique=False)
    op.create_table('habit_streaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('habit_type', sa.String(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('max_streak', sa.Integer(), nullable=True),
    sa.Column('last_completed_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habit_streaks_habit_type'), 'habit_streaks', ['habit_type'], unique=False)
    op.create_index(op.f('ix_habit_streaks_id'), 'habit_streaks', ['id'], unique=False)
    op.create_table('lab_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('analysis_summary', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_reports_id'), 'lab_reports', ['id'], unique=False)
    op.create_index(op.f('ix_lab_reports_report_type'), 'lab_reports', ['report_type'], unique=False)
    op.create_table('micronutrient_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('nutrient_name', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('source_food_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_micronutrient_logs_id'), 'micronutrient_logs', ['id'], unique=False)
    op.create_index(op.f('ix_micronutrient_logs_nutrient_name'), 'micronutrient_logs', ['nutrient_name'], unique=False)
    op.create_table('nutrition_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('daily_calories_target', sa.Integer(), nullable=True),
    sa.Column('protein_target', sa.Integer(), nullable=True),
    sa.Column('carbs_target', sa.Integer(), nullable=True),
    sa.Column('fats_target', sa.Integer(), nullable=True),
    sa.Column('meal_plan_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_plans_id'), 'nutrition_plans', ['id'], unique=False)
    op.create_table('performance_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('readiness_score', sa.Float(), nullable=True),
    sa.Column('hybrid_balance_score', sa.Float(), nullable=True),
    sa.Column('fatigue_index', sa.Float(), nullable=True),
    sa.Column('injury_risk', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_scores_id'), 'performance_scores', ['id'], unique=False)
    op.create_table('recovery_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('sleep_debt', sa.Float(), nullable=True),
    sa.Column('hrv_trend', sa.Float(), nullable=True),
    sa.Column('stress_score', sa.Float(), nullable=True),
    sa.Column('recovery_index', sa.Float(), nullable=True),
    sa.Column('total_sleep_minutes', sa.Integer(), nullable=True),
    sa.Column('deep_sleep_minutes', sa.Integer(), nullable=True),
    sa.Column('rem_sleep_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_scores_id'), 'recovery_scores', ['id'], unique=False)
    op.create_table('symptom_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('symptom_name', sa.String(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symptom_logs_id'), 'symptom_logs', ['id'], unique=False)
    op.create_index(op.f('ix_symptom_logs_symptom_name'), 'symptom_logs', ['symptom_name'], unique=False)
    op.create_table('wearable_sync_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('expires_in', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wearable_sync_status_id'), 'wearable_sync_status', ['id'], unique=False)
    op.create_index(op.f('ix_wearable_sync_status_provider'), 'wearable_sync_status', ['provider'], unique=False)
    op.create_table('community_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_comments_id'), 'community_comments', ['id'], unique=False)
    op.drop_index('ix_athletestate_id', table_name='athletestate')
    op.drop_table('athletestate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athletestate',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('cns_fatigue', sa.FLOAT(), nullable=True),
    sa.Column('muscular_fatigue_upper', sa.FLOAT(), nullable=True),
    sa.Column('muscular_fatigue_lower', sa.FLOAT(), nullable=True),
    sa.Column('cardio_fatigue', sa.FLOAT(), nullable=True),
    sa.Column('current_mesocycle_phase', sa.VARCHAR(length=12), nullable=True),
    sa.Column('week_in_phase', sa.INTEGER(), nullable=True),
    sa.Column('last_workout_date', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_athletestate_id', 'athletestate', ['id'], unique=False)
    op.drop_index(op.f('ix_community_comments_id'), table_name='community_comments')
    op.drop_table('community_comments')
    op.drop_index(op.f('ix_wearable_sync_status_provider'), table_name='wearable_sync_status')
    op.drop_index(op.f('ix_wearable_sync_status_id'), table_name='wearable_sync_status')
    op.drop_table('wearable_sync_status')
    op.drop_index(op.f('ix_symptom_logs_symptom_name'), table_name='symptom_logs')
    op.drop_index(op.f('ix_symptom_logs_id'), table_name='symptom_logs')
    op.drop_table('symptom_logs')
    op.drop_index(op.f('ix_recovery_scores_id'), table_name='recovery_scores')
    op.drop_table('recovery_scores')
    op.drop_index(op.f('ix_performance_scores_id'), table_name='performance_scores')
    op.drop_table('performance_scores')
    op.drop_index(op.f('ix_nutrition_plans_id'), table_name='nutrition_plans')
    op.drop_table('nutrition_plans')
    op.drop_index(op.f('ix_micronutrient_logs_nutrient_name'), table_name='micronutrient_logs')
    op.drop_index(op.f('ix_micronutrient_logs_id'), table_name='micronutrient_logs')
    op.drop_table('micronutrient_logs')
    op.drop_index(op.f('ix_lab_reports_report_type'), table_name='lab_reports')
    op.drop_index(op.f('ix_lab_reports_id'), table_name='lab_reports')
    op.drop_table('lab_reports')
    op.drop_index(op.f('ix_habit_streaks_id'), table_name='habit_streaks')
    op.drop_index(op.f('ix_habit_streaks_habit_type'), table_name='habit_streaks')
    op.drop_table('habit_streaks')
    op.drop_index(op.f('ix_daily_habit_logs_id'), table_name='daily_habit_logs')
    op.drop_index(op.f('ix_daily_habit_logs_habit_type'), table_name='daily_habit_logs')
    op.drop_table('daily_habit_logs')
    op.drop_index(op.f('ix_community_posts_id'), table_name='community_posts')
    op.drop_table('community_posts')
    op.drop_index(op.f('ix_biometric_timeseries_metric_type'), table_name='biometric_timeseries')
    op.drop_index(op.f('ix_biometric_timeseries_id'), table_name='biometric_timeseries')
    op.drop_table('biometric_timeseries')
    # ### end Alembic commands ###
